config/urls.py
"""Main URLs module."""

from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    # Django Admin
    path(settings.ADMIN_URL, admin.site.urls),

    # Local
    path('', include(('spotify.users.urls', 'users'), namespace='users')),
    path('music/', include(('spotify.music.urls', 'music'), namespace='music')),
    path('playLists/', include(('spotify.playLists.urls', 'playList'), namespace='playLists')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spotify/music/urls.py
"""Music URL's."""

# Django
from django.urls import path

# Views
from spotify.music import views


urlpatterns = [
    # Management
    path(
        route='search/',
        view=views.search,
        name='search'
    ),
    path(
        route='favorites/',
        view=views.Favorites.as_view(),
        name='myFavorite'
    ),
    path(
        route='playMusic/',
        view=views.play,
        name='playMusic'
    ),
    path(
        route='myLibrary/',
        view=views.MyLibrary.as_view(),
        name='myLibrary'
    ),
]

spotify/playLists/urls.py
"""Play Lists URL's."""

# Django
from django.urls import path

# Views
from spotify.playLists import views


urlpatterns = [
    # Management
    path(
        route='addTrack/<str:title>',
        view=views.add_track,
        name='addTrack'
    ),
    path(
        route='addFavorite/<str:title>',
        view=views.add_favorite_track,
        name='addFavorite'
    ),
]

spotify/users/urls.py
"""Users URL's."""

# Django
from django.urls import path

# Views
from spotify.users import views


urlpatterns = [
    # Management

    path(
        route='',
        view=views.feed,
        name='feed'
    ),
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route="user/<str:username>/",
        view=views.UpdateProfileView.as_view(),
        name="update"
    ),
]

spotify/music/models/tracks.py
"""Tracks model."""

# Django
from django.db import models

# Utils
from spotify.utils.base_model import BaseModel


class TrackModel(BaseModel):
    """Tracks Model."""
    artist = models.CharField(
        'Artist song',
        max_length=150,
    )
    title = models.CharField(
        'Song title',
        max_length=100,
    )
    album = models.CharField(
        'Album name',
        max_length=100,
    )
    duration = models.CharField(
        'Duration time song',
        max_length=100
    )

    def __str__(self):
        """Return track name."""
        return self.title

spotify/playLists/models/usersPlayLists.py
"""Users Play Lists Relationships."""

# Django
from django.db import models

# Utils
from spotify.utils.base_model import BaseModel


class PlayLists(BaseModel):
    """Users Play List Storage."""
    user = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
    )
    track = models.ForeignKey(
        'music.TrackModel',
        on_delete=models.CASCADE,
    )
    is_favorite = models.BooleanField(
        default=False
    )

    def __str__(self):
        """Return user PlayList"""
        return (
            f"'username': {self.user}, "
            f"'is_favorite': {self.is_favorite}, "
            f"'title': {self.track.title}, "
            f"'album': {self.track.album}, "
            f"'duration': {self.track.duration}"
        )

spotify/users/models.py
"""Users model."""

# Django
from django.db import models
from django.contrib.auth.models import AbstractUser

# Utilities
from spotify.utils.base_model import BaseModel


class User(BaseModel, AbstractUser):
    """User model.

    Extend from Django's Abstract User.
    """

    email = models.EmailField('email address', unique=True)
    is_membership = models.BooleanField(
        'client',
        default=False,
        help_text=(
            'Help easily distinguish users and perform queries. '
            'Clients are the main type of user.'
        )
    )
    is_verified = models.BooleanField(
        'verified',
        default=True,
        help_text='Set to true when the user have verified its email address.'
    )
    birthday = models.DateField(
        'birthday',
        blank=True,
        null=True,
    )
    country = models.CharField(
        max_length=50,
        null=True,
        blank=True,
    )
    picture = models.ImageField(
        upload_to='users/pictures',
        blank=True,
        null=True
    )

    def __str__(self):
        """Return username."""
        return self.username

spotify/users/models/users.py
"""Users model."""

# Django
from django.db import models
from django.contrib.auth.models import AbstractUser

# Utilities
from spotify.utils.base_model import BaseModel


class User(BaseModel, AbstractUser):
    """User model.

    Extend from Django's Abstract User.
    """

    email = models.EmailField('email address', unique=True)
    is_membership = models.BooleanField(
        'client',
        default=True,
        help_text=(
            'Help easily distinguish users and perform queries. '
            'Clients are the main type of user.'
        )
    )
    is_verified = models.BooleanField(
        'verified',
        default=True,
        help_text='Set to true when the user have verified its email address.'
    )
    birthdate = models.DateField(
        'Birthdate',
        blank=True,
        null=True,
    )

    def __str__(self):
        """Return username."""
        return self.username

spotify/users/forms.py
""""Forms to User"""

# Django
from django import forms

# Models
from spotify.users.models import User


class SignupForm(forms.Form):
    """Sign up form."""

    username = forms.CharField(min_length=4, max_length=50)
    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean_email(self):
        """Email must be unique."""
        email = self.cleaned_data['email']
        email_taken = User.objects.filter(email=email).exists()
        if email_taken:
            raise forms.ValidationError('Email is already in use.')
        return email

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']
        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')
        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')
        User.objects.create_user(**data)

spotify/users/forms/users.py
""""Forms to User"""

# Django
from django import forms

# Models
from spotify.users.models import User


class SignupForm(forms.Form):
    """Sign up form."""

    username = forms.CharField(min_length=4, max_length=50)
    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean_email(self):
        """Email must be unique."""
        email = self.cleaned_data['email']
        email_taken = User.objects.filter(email=email).exists()
        if email_taken:
            raise forms.ValidationError('Email is already in use.')
        return email

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']
        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')
        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')
        User.objects.create_user(**data)

spotify/music/views.py
"""Music views."""

# Django
from django.shortcuts import render
from django.views.generic import ListView

# Models
from spotify.playLists.models import PlayLists

# Utils
import json
from spotify.scraping.scraping import get_info_by_search_name, get_token


def search(request):
    """View search"""
    try:
        data_search = json.loads(get_info_by_search_name(request.GET['search'],  get_token()))
        track = data_search['track']
        artist = data_search['artist']
        album = data_search['album']
        context = {
            'track': track,
            'artist': artist,
            'album': album,
        }
    except:
        context = {
            'track': None,
            'artist': None,
            'album': None,
        }

    return render(
        request=request,
        template_name='music/search.html',
        context=context,
    )


class MyLibrary (ListView):
    """Display list user favorite Library."""
    model = PlayLists
    context_object_name = 'MyLibrary'
    template_name = 'music/myLibrary.html'

    def get_queryset(self):
        q = PlayLists.objects.filter(user__username=self.request.user.username)
        return q


def play(request):
    data = {
        'title': 'BitâKora 5: Marcas en tiempos de COVID, Elon Musk y Bose.',
        'album': 'Podcast',
        'artist': 'Nadia Molina',
        'duration': '47:89:14',
    }

    return render(
        request=request,
        template_name='music/play.html',
        context={'data': data},
    )


def save():
    pass


class Favorites (ListView):
    """Display list user favorite songs."""
    model = PlayLists
    context_object_name = 'my_favorites'
    template_name = 'music/favorites.html'

    def get_queryset(self):
        q = PlayLists.objects.filter(user__username=self.request.user.username, is_favorite=True)
        return q

spotify/playLists/views.py
"""PlayLists views."""

# Django
from django.shortcuts import redirect

# Models
from spotify.music.models import TrackModel
from spotify.playLists.models import PlayLists

# Utils
import json
from spotify.scraping.scraping import get_info_by_search_name, get_token


TOKEN = '123'
TRACK = None


def add_track(request, title):
    """View test"""
    track_exist = search_track(title)
    user = request.user

    if track_exist:
        add_in_user_library(user, TRACK)
    else:
        obtain_token()
        save_track_in_db(title)
        add_in_user_library(user, TRACK)

    return redirect('music:myLibrary')


def search_track(title):
    global TRACK
    try:
        TRACK = TrackModel.objects.get(title=title)
        return True
    except TrackModel.DoesNotExist:
        return False


def add_in_user_library(user, track):
    user_have_track = PlayLists.objects.filter(user=user, track=track)

    if not user_have_track.exists():
        PlayLists.objects.create(user=user, track=track)


def save_track_in_db(title):
    global TRACK
    data_track = json.loads(get_info_by_search_name(title, TOKEN))
    TRACK = TrackModel.objects.create(
        artist=data_track['track']['artist'],
        title=data_track['track']['title'],
        album=data_track['track']['album'],
        duration=data_track['track']['duration'],
    )


def obtain_token():
    global TOKEN
    TOKEN = get_token()


def add_favorite_track(request, title):
    PlayLists.objects.filter(user=request.user, track__title=title).update(is_favorite=True)
    return redirect('music:myLibrary')

spotify/users/views.py
"""Uses views."""

# Django
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import FormView, UpdateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Forms
from spotify.users.forms import SignupForm

# Models
from spotify.users.models import User

# Utils
import json
from spotify.scraping.scraping import get_info_by_artist_name, get_token


class LoginView(auth_views.LoginView):
    """Login view."""
    template_name = 'users/login.html'


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout view."""

    template_name = 'users/logged_out.html'


class SignupView(FormView):
    """Users sign up view."""

    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """Update profile view."""
    slug_field = 'username'
    slug_url_kwarg = 'username'

    template_name = 'users/update.html'
    model = User
    fields = ['first_name', 'last_name', 'birthday', 'country', 'picture']

    def get_object(self):
        """Return user's profile."""
        return self.request.user

    def get_success_url(self):
        """Return to user's profile."""
        username = self.object
        return reverse('users:update', kwargs={'username': username})


@login_required()
def feed(request):
    data_feed = json.loads(get_info_by_artist_name(get_token()))
    data = data_feed

    return render(
        request=request,
        template_name='index.html',
        context={'data': data},
    )

spotify/templates/users/signup.html
<html>
<head>
  <title>Sign up</title>

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/signup.css' %}" />
</head>
<body>
<div>
    <div>
        <div class="head">
            <a class="spotify-logo" title="Spotify" href="/"></a>
        </div>
    </div>
    <div class="content">
        <div class="row">
            <h2 class="text-center">Sign up for free to start listening.</h2>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <a href="/" class="btn btn-block btn-facebook">Sign up with Facebook</a>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="divider">
                    <span class="divider-title">or</span>
                </div>
            </div>
        </div>
        <form action="{% url 'users:signup' %}" method="POST">
            {% csrf_token %} {{ form.non_field_errors }} {{ form.email.errors }}
            <h3 class="text-center">Sign up with your email address</h3>
            <div class="row">
                <div class="col-xs-12">
                    <label for="{{ form.email.id_for_label }}" class="h3">What's your email?</label>
                    {{ form.email }}
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <label for="{{ form.password.id_for_label }}" class="h3">Create a password</label>
                    {{ form.password }}
                </div>

            </div>
            <div class="row">
                <div class="col-xs-12">
                    <label for="{{ form.password_confirmation.id_for_label }}" class="h3">Confirm your password</label>
                    {{ form.password_confirmation }}
                </div>

            </div>

            <div class="row">
                <div class="col-xs-12">
                    {{ form.username.errors }}
                    <label for="{{ form.username.id_for_label }}" class="h3">What should we call you?</label>
                    {{ form.username }}
                </div>

            </div>
            <div class="row row-submit">
                <div class="col-xs-12">
                    <div class="checkbox">
                        <label>
                          <input type="checkbox" name="thirdParty" class="checkbox">
                          <span class="control-indicator"></span>
                          <span class="">Share my registration data with Spotify's content providers for marketing purposes.</span>
                      </label>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <p class="text-center text-muted"><span class="">By clicking on Sign up, you agree to Spotify's <a href="/" target="_blank">Terms and Conditions of Use</a>.</span></p>
                            <p class="text-center text-muted"><span class="">To learn more about how Spotify collects, uses, shares and protects your personal data please read Spotify's <a href="/" target="_blank">Privacy Policy</a>.</span></p>
                            <div class=""><button type="submit" class="btn btn-block btn-green">Sign up</button></div>
                            <p class="text-center"><span class="">Have an account? <a href="{% url 'users:login' %}">Log in</a>.</span></p>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
</body>
</html>

spotify/templates/users/update.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;600;700;800&display=swap"
      rel="stylesheet"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/overview-page.css' %}" />
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}" />
    <title>Vista General de la Cuenta - Spotify</title>
  </head>
  <body>
    <!-- Header start ****   -->
    <header class="header">
      <div class="container__nav">
        <div class="nav__logo">
          <a href="{% url 'users:feed' %}">
            <img
              src="{% static 'images/Spotify_Logo_RGB_White.png' %}"
              alt="Logo Spotify"
            />
          </a>
        </div>
        <nav class="nav__contain">
          <ul>
            <li>Premium</li>
            <li>Ayuda</li>
            <li>Descargar</li>
            <li>|</li>
            <li>
              {% if user.picture %}
              <img src="{{ user.picture.url }}" alt="Profile picture" />
              {% else%}
              <img
                src="{% static 'images/default-profile.png' %}"
                alt="Profile picture"
              />
              {% endif %}
            </li>
            <li>
              <a target="_blank"
                >Perfil
                <i class="icon-circle-down"></i>
              </a>
              <div class="services-submenu">
                <div class="submenu-items">
                  <a href="{% url 'users:logout' %}" type="submit"
                    >Cerrar Sesión</a
                  >
                </div>
              </div>
            </li>
          </ul>
        </nav>
      </div>
    </header>
    <!-- Header end ****   -->

    <!-- menu account start ****   -->
    <main class="account__container">
      <aside class="account__container--menu">
        <div class="account__photo">
          {% if user.picture %}
          <img src="{{ user.picture.url }}" />
          {% else%}
          <img src="{% static 'images/default-profile.png' %}" />
          {% endif %}
        </div>
        <div class="account__blocks">
          <span class="account__blocks--line"></span>
          <div class="account__blocks--item">
            <span class="account__blocks--icon icon-home"></span>
            <p>Vista general de la cuenta</p>
          </div>
        </div>
        <div class="account__blocks">
          <span class="account__blocks--line"></span>
          <div class="account__blocks--item">
            <span class="account__blocks--icon icon-pencil"></span>
            <p>Editar perfil</p>
          </div>
        </div>
        <div class="account__blocks">
          <span class="account__blocks--line"></span>
          <div class="account__blocks--item">
            <span class="account__blocks--icon icon-lock"></span>
            <p>Cambiar contraseña</p>
          </div>
        </div>
        <div class="account__blocks">
          <span class="account__blocks--line"></span>
          <div class="account__blocks--item">
            <span class="account__blocks--icon icon-bell"></span>
            <p>Configuración de notificaciones</p>
          </div>
        </div>
        <div class="account__blocks">
          <span class="account__blocks--line"></span>
          <div class="account__blocks--item">
            <span class="account__blocks--icon icon-lock"></span>
            <p>Configuración de privacidad</p>
          </div>
        </div>
        <div class="account__blocks">
          <span class="account__blocks--line"></span>
          <div class="account__blocks--item">
            <span class="account__blocks--icon icon-spinner11"></span>
            <p>Recuperar playlist</p>
          </div>
        </div>
        <div class="account__blocks">
          <span class="account__blocks--line"></span>
          <div class="account__blocks--item">
            <span class="account__blocks--icon icon-coin-dollar"></span>
            <p>Recibos</p>
          </div>
        </div>
        <div class="account__blocks">
          <span class="account__blocks--line"></span>
          <div class="account__blocks--item">
            <span class="account__blocks--icon icon-mobile"></span>
            <p>Apps</p>
          </div>
        </div>
        <div class="account__blocks">
          <span class="account__blocks--line"></span>
          <div class="account__blocks--item">
            <span class="account__blocks--icon icon-magic-wand"></span>
            <p>Utilizar</p>
          </div>
        </div>
      </aside>
      <!-- menu account end ****   -->

      <!-------- account description start  ---------->
      <section class="account__description">
        <h1 class="account__description--title">
          Vista general de la cuenta
        </h1>
        <div class="account__description--profile">
          <h1>Perfil</h1>
        </div>
        <div class="account__description--profile-item">
          <!-------- Fix this section need stay into a form  ---->
          <form
            action="{% url 'users:update' user.username %}"
            method="POST"
            enctype="multipart/form-data"
          >
            {% csrf_token %}

            <div class="account__description--profile-item">
              <label>Foto de perfil </label>
              {% if user.picture %}
              <img src="{{ user.picture.url }}" />
              {% else%}
              <img
                src="{% static 'images/default-profile.png' %}"
                class=""
                height="50"
              />
              {% endif %}
              <p>
                <input type="file" name="picture" />
              </p>
            </div>

            <div class="account__description--profile-item">
              <label>Primer Nombre</label>
              <div class="item-input">
                <input
                  type="text"
                  name="first_name"
                  placeholder="First name"
                  value="{% if form.errors %}{{ form.first_name.value }}{% else %}{{ user.first_name }}{% endif %}"
                />
                <div class="">
                  {% for error in form.first_name.errors %} {{ error }}
                  {%endfor%}
                </div>
              </div>
            </div>

            <div class="account__description--profile-item">
              <label>Apellidos</label>
              <div class="item-input">
                <input
                  class=""
                  type="text"
                  name="last_name"
                  placeholder="Last name"
                  value="{% if form.errors %}{{ form.last_name.value }}{% else %}{{ user.last_name }}{% endif %}"
                />
                <div class="">
                  {% for error in form.last_name.errors %} {{ error }}
                  {%endfor%}
                </div>
              </div>
            </div>

            <div class="account__description--profile-item">
              <label>Fecha de Nacimiento <small>(aaaa-mm-dd)</small></label>
              <div class="item-input">
                <input
                  class=""
                  type="text"
                  name="birthday"
                  placeholder="Birthday"
                  value="{% if form.errors %}{{ form.birthday.value }}{% else %}{{ user.birthday }}{% endif %}"
                />
                <div class="">
                  {% for error in form.birthday.errors %} {{ error }}
                  {%endfor%}
                </div>
              </div>
            </div>

            <div class="account__description--profile-item">
              <label>País</label>
              <div class="item-input">
                <input
                  class=""
                  type="text"
                  name="country"
                  placeholder="Country"
                  value="{% if form.errors %}{{ form.country.value }}{% else %}{{ user.country }}{% endif %}"
                />
                <div class="">
                  {% for error in form.country.errors %} {{ error }} {% endfor%}
                </div>
              </div>
            </div>
            <button type="submit" class="button__outline">Update info</button>
          </form>
        </div>

        <div class="account__description--plan">
          <h1>Tu plan</h1>
        </div>
        <div class="account__description--plan-container">
          <div class="account__description--plan-type">
            <h1>Spotify Free</h1>
          </div>
          <p>Escucha música solo en modo aleatorio y con anuncios.</p>
          <h2>Gratis</h2>
        </div>
        <a href="#" class="button__outline--plan" type="submit"
          >Unirte a premium</a
        >
        <div class="account__description--session">
          <h1>Cierra sesión en cualquier parte</h1>
          <p>
            Cierra sesión donde sea que tengas Spotify abierto, es decir, en el
            sitio web, en tu celular, en tu computadora o en cualquier otro
            dispositivo.
          </p>
        </div>
        <div class="account__description--session-info">
          <p>
            Importante: Esto no incluye dispositivos de socios, como Sonos y
            PlayStation. Para obtener más información sobre cómo cerrar tu
            sesión (o desvincular tu cuenta) de Spotify en un dispositivo
            fabricado por uno de nuestros socios, consulta el manual del
            fabricante del dispositivo.
          </p>
        </div>
        <a
          href="{% url 'users:logout' %}"
          class="button__outline--session"
          type="submit"
          >Cierra sesión en todas partes</a
        >
      </section>
    </main>
    <!------- account description end  -------->
    <!---------------- footer start  ------------------------>
    <footer class="footer">
      <div class="footer__container">
        <div class="footer__margin--top"></div>
        <div class="footer__logo">
          <a href="https://open.spotify.com/">
            <img
              src="{% static 'images/Spotify_Logo_RGB_White.png' %}"
              alt=""
            />
          </a>
        </div>
        <div class="footer__title--one">
          <p>compañía</p>
        </div>
        <div class="footer__company">
          <div class="footer__company--item">
            <ul>
              <li>Acerca de</li>
              <li>Empleo</li>
              <li>For the record</li>
            </ul>
          </div>
        </div>
        <div class="footer__title--two">
          <p>comunidades</p>
        </div>
        <div class="footer__communities">
          <div class="footer__communities--item">
            <ul>
              <li>Servicios para artistas</li>
              <li>Desarrolladores</li>
              <li>Marcas</li>
              <li>Inversionistas</li>
              <li>Proveedores</li>
            </ul>
          </div>
        </div>
        <div class="footer__title--three">
          <p>Enlaces útiles</p>
        </div>
        <div class="footer__links">
          <div class="footer__links--item">
            <ul>
              <li>Ayuda</li>
              <li>Reproductor Web</li>
              <li>App móvil gratis</li>
            </ul>
          </div>
        </div>
        <div class="footer__social">
          <div class="footer__social--icons">
            <i class="icon-instagram icons-circle"></i>
            <i class="icon-twitter icons-circle"></i>
            <i class="icon-facebook icons-circle"></i>
          </div>
        </div>
        <div class="footer__disclaimer">
          <div class="footer__disclaimer--items">
            <ul>
              <li>Legal</li>
              <li>Centro de Privacidad</li>
              <li>Política de Privacidad</li>
              <li>Cookies</li>
              <li>Sobre los anuncios</li>
            </ul>
          </div>
        </div>
        <div class="footer__country">
          <div class="footer__country--item">
            <ul>
              <li>
                Colombia
                <span
                  ><img src="https://country-flags.scdn.co/flags/co.svg" alt=""
                /></span>
              </li>
              <li>© 2020 Spotify AB</li>
            </ul>
          </div>
        </div>
        <div class="footer__margin--bottom"></div>
      </div>
    </footer>
    <!---------------- footer end ------------------------>
  </body>
</html>