config/urls.py
"""Main URLs module."""

from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    # Django Admin
    path(settings.ADMIN_URL, admin.site.urls),

    # Local
    path('', include(('spotify.users.urls', 'users'), namespace='users')),
    path('music/', include(('spotify.music.urls', 'music'), namespace='music')),
    path('playLists/', include(('spotify.playLists.urls', 'playList'), namespace='playLists')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spotify/music/urls.py
"""Music URL's."""

# Django
from django.urls import path

# Views
from spotify.music import views


urlpatterns = [
    # Management
    path(
        route='search/',
        view=views.search,
        name='search'
    ),
    path(
        route='favorites/',
        view=views.Favorites.as_view(),
        name='myFavorite'
    ),
    path(
        route='playMusic/',
        view=views.play,
        name='playMusic'
    ),
    path(
        route='myLibrary/',
        view=views.MyLibrary.as_view(),
        name='myLibrary'
    ),
]

spotify/playLists/urls.py
"""Play Lists URL's."""

# Django
from django.urls import path

# Views
from spotify.playLists import views


urlpatterns = [
    # Management
    path(
        route='addTrack/<str:title>',
        view=views.add_track,
        name='addTrack'
    ),
    path(
        route='addFavorite/<str:title>',
        view=views.add_favorite_track,
        name='addFavorite'
    ),
]

spotify/users/urls.py
"""Users URL's."""

# Django
from django.urls import path

# Views
from spotify.users import views


urlpatterns = [
    # Management

    path(
        route='',
        view=views.feed,
        name='feed'
    ),
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route="user/<str:username>/",
        view=views.UpdateProfileView.as_view(),
        name="update"
    ),
]

spotify/music/models/tracks.py
"""Tracks model."""

# Django
from django.db import models

# Utils
from spotify.utils.base_model import BaseModel


class TrackModel(BaseModel):
    """Tracks Model."""
    artist = models.CharField(
        'Artist song',
        max_length=150,
    )
    title = models.CharField(
        'Song title',
        max_length=100,
    )
    album = models.CharField(
        'Album name',
        max_length=100,
    )
    duration = models.CharField(
        'Duration time song',
        max_length=100
    )

    def __str__(self):
        """Return track name."""
        return self.title

spotify/playLists/models/usersPlayLists.py
"""Users Play Lists Relationships."""

# Django
from django.db import models

# Utils
from spotify.utils.base_model import BaseModel


class PlayLists(BaseModel):
    """Users Play List Storage."""
    user = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
    )
    track = models.ForeignKey(
        'music.TrackModel',
        on_delete=models.CASCADE,
    )
    is_favorite = models.BooleanField(
        default=False
    )

    def __str__(self):
        """Return user PlayList"""
        return (
            f"'username': {self.user}, "
            f"'is_favorite': {self.is_favorite}, "
            f"'title': {self.track.title}, "
            f"'album': {self.track.album}, "
            f"'duration': {self.track.duration}"
        )

spotify/users/models.py
"""Users model."""

# Django
from django.db import models
from django.contrib.auth.models import AbstractUser

# Utilities
from spotify.utils.base_model import BaseModel


class User(BaseModel, AbstractUser):
    """User model.

    Extend from Django's Abstract User.
    """

    email = models.EmailField('email address', unique=True)
    is_membership = models.BooleanField(
        'client',
        default=False,
        help_text=(
            'Help easily distinguish users and perform queries. '
            'Clients are the main type of user.'
        )
    )
    is_verified = models.BooleanField(
        'verified',
        default=True,
        help_text='Set to true when the user have verified its email address.'
    )
    birthday = models.DateField(
        'birthday',
        blank=True,
        null=True,
    )
    country = models.CharField(
        max_length=50,
        null=True,
        blank=True,
    )
    picture = models.ImageField(
        upload_to='users/pictures',
        blank=True,
        null=True
    )

    def __str__(self):
        """Return username."""
        return self.username

spotify/users/models/users.py
"""Users model."""

# Django
from django.db import models
from django.contrib.auth.models import AbstractUser

# Utilities
from spotify.utils.base_model import BaseModel


class User(BaseModel, AbstractUser):
    """User model.

    Extend from Django's Abstract User.
    """

    email = models.EmailField('email address', unique=True)
    is_membership = models.BooleanField(
        'client',
        default=True,
        help_text=(
            'Help easily distinguish users and perform queries. '
            'Clients are the main type of user.'
        )
    )
    is_verified = models.BooleanField(
        'verified',
        default=True,
        help_text='Set to true when the user have verified its email address.'
    )
    birthdate = models.DateField(
        'Birthdate',
        blank=True,
        null=True,
    )

    def __str__(self):
        """Return username."""
        return self.username

spotify/users/forms.py
""""Forms to User"""

# Django
from django import forms

# Models
from spotify.users.models import User


class SignupForm(forms.Form):
    """Sign up form."""

    username = forms.CharField(min_length=4, max_length=50)
    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean_email(self):
        """Email must be unique."""
        email = self.cleaned_data['email']
        email_taken = User.objects.filter(email=email).exists()
        if email_taken:
            raise forms.ValidationError('Email is already in use.')
        return email

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']
        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')
        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')
        User.objects.create_user(**data)

spotify/users/forms/users.py
""""Forms to User"""

# Django
from django import forms

# Models
from spotify.users.models import User


class SignupForm(forms.Form):
    """Sign up form."""

    username = forms.CharField(min_length=4, max_length=50)
    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean_email(self):
        """Email must be unique."""
        email = self.cleaned_data['email']
        email_taken = User.objects.filter(email=email).exists()
        if email_taken:
            raise forms.ValidationError('Email is already in use.')
        return email

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']
        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')
        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')
        User.objects.create_user(**data)

spotify/music/views.py
"""Music views."""

# Django
from django.shortcuts import render
from django.views.generic import ListView

# Models
from spotify.playLists.models import PlayLists

# Utils
import json
from spotify.scraping.scraping import get_info_by_search_name, get_token


def search(request):
    """View search"""
    try:
        data_search = json.loads(get_info_by_search_name(request.GET['search'],  get_token()))
        track = data_search['track']
        artist = data_search['artist']
        album = data_search['album']
        context = {
            'track': track,
            'artist': artist,
            'album': album,
        }
    except:
        context = {
            'track': None,
            'artist': None,
            'album': None,
        }

    return render(
        request=request,
        template_name='music/search.html',
        context=context,
    )


class MyLibrary (ListView):
    """Display list user favorite Library."""
    model = PlayLists
    context_object_name = 'MyLibrary'
    template_name = 'music/myLibrary.html'

    def get_queryset(self):
        q = PlayLists.objects.filter(user__username=self.request.user.username)
        return q


def play(request):
    data = {
        'title': 'BitâKora 5: Marcas en tiempos de COVID, Elon Musk y Bose.',
        'album': 'Podcast',
        'artist': 'Nadia Molina',
        'duration': '47:89:14',
    }

    return render(
        request=request,
        template_name='music/play.html',
        context={'data': data},
    )


def save():
    pass


class Favorites (ListView):
    """Display list user favorite songs."""
    model = PlayLists
    context_object_name = 'my_favorites'
    template_name = 'music/favorites.html'

    def get_queryset(self):
        q = PlayLists.objects.filter(user__username=self.request.user.username, is_favorite=True)
        return q

spotify/playLists/views.py
"""PlayLists views."""

# Django
from django.shortcuts import redirect

# Models
from spotify.music.models import TrackModel
from spotify.playLists.models import PlayLists

# Utils
import json
from spotify.scraping.scraping import get_info_by_search_name, get_token


TOKEN = '123'
TRACK = None


def add_track(request, title):
    """View test"""
    track_exist = search_track(title)
    user = request.user

    if track_exist:
        add_in_user_library(user, TRACK)
    else:
        obtain_token()
        save_track_in_db(title)
        add_in_user_library(user, TRACK)

    return redirect('music:myLibrary')


def search_track(title):
    global TRACK
    try:
        TRACK = TrackModel.objects.get(title=title)
        return True
    except TrackModel.DoesNotExist:
        return False


def add_in_user_library(user, track):
    user_have_track = PlayLists.objects.filter(user=user, track=track)

    if not user_have_track.exists():
        PlayLists.objects.create(user=user, track=track)


def save_track_in_db(title):
    global TRACK
    data_track = json.loads(get_info_by_search_name(title, TOKEN))
    TRACK = TrackModel.objects.create(
        artist=data_track['track']['artist'],
        title=data_track['track']['title'],
        album=data_track['track']['album'],
        duration=data_track['track']['duration'],
    )


def obtain_token():
    global TOKEN
    TOKEN = get_token()


def add_favorite_track(request, title):
    PlayLists.objects.filter(user=request.user, track__title=title).update(is_favorite=True)
    return redirect('music:myLibrary')

spotify/users/views.py
"""Uses views."""

# Django
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import FormView, UpdateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Forms
from spotify.users.forms import SignupForm

# Models
from spotify.users.models import User

# Utils
import json
from spotify.scraping.scraping import get_info_by_artist_name, get_token


class LoginView(auth_views.LoginView):
    """Login view."""
    template_name = 'users/login.html'


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout view."""

    template_name = 'users/logged_out.html'


class SignupView(FormView):
    """Users sign up view."""

    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """Update profile view."""
    slug_field = 'username'
    slug_url_kwarg = 'username'

    template_name = 'users/update.html'
    model = User
    fields = ['first_name', 'last_name', 'birthday', 'country', 'picture']

    def get_object(self):
        """Return user's profile."""
        return self.request.user

    def get_success_url(self):
        """Return to user's profile."""
        username = self.object
        return reverse('users:update', kwargs={'username': username})


@login_required()
def feed(request):
    data_feed = json.loads(get_info_by_artist_name(get_token()))
    data = data_feed

    return render(
        request=request,
        template_name='index.html',
        context={'data': data},
    )

spotify/templates/music/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail a Play List</title>
</head>
<body>

  <h1>5. Pantalla de detalle de las listas de reproducción, canciones o albumes</h1>
  <h2>5. El usuario puede escuchar la música que ha seleccionado</h2>


   {% for item in data %}
     <span style="background-color: olivedrab"> {{ item.name_track }}</span>
   {% endfor %}
</body>
</html>

spotify/templates/music/favorites.html
{% extends "base.html" %}

{% block head_content %}
  <title>My Favorites</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/favorites.css' %}">
{% endblock%}

{% block container %}
  <div class="search__genres--title">
      <h2>Canciones Favoritas</h2>
  </div>

  <button class="play-button">Play</button>

  <div class="favorites__explore--container">
      <div class="table-title">
          <!-- play -->
      </div>
      <div class="table-title">
          <!-- like -->
      </div>
      <div class="table-title">
          <p>Título</p>
      </div>
      <div class="table-title">
          <p>Artista</p>
      </div>
      <div class="table-title">
          <p>Album</p>
      </div>
      <div class="table-title">
          <!-- Duración -->
          <i class="fa fa-clock-o icon"></i>
      </div>
  </div>

  <div class="fav-results">
      {% for item in my_favorites %}
      <div class="table-content">
          <div class="table-content__text">
              <div class="play-icon">
                  <i class="fa fa-play-circle-o"></i>
              </div>
          </div>
          <div class="table-content__text">
              <!-- like -->
              <div class="table-content__text--like">
                  <i class="fa fa-heart"></i>
              </div>
          </div>
          <div class="table-content__text">
              <p>{{ item.track.title }}</p>
          </div>
          <div class="table-content__text">
              <p>{{ item.track.artist }}</p>
          </div>
          <div class="table-content__text">
              <p>{{ item.track.album }}</p>
          </div>
          <div class="table-content__text">
              <p>{{ item.track.duration }}</p>
          </div>
      </div>
      {% endfor %}
  </div>
{% endblock %}

spotify/templates/music/myLibrary.html
{% extends "base.html" %}

{% block head_content %}
  <title>Library</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/library.css' %}">
{% endblock%}

{% block container %}
  <div class="search__genres--title">
    <h2>Biblioteca</h2>
  </div>

  <div class="library__explore--container">
      <div class="table-title">
          <p> #</p>
      </div>
      <div class="table-title">
          <!-- like -->
      </div>
      <div class="table-title">
          <p>Título</p>
      </div>
      <div class="table-title">
          <!-- Duración -->
          <i class="fa fa-clock-o icon"></i>
      </div>
  </div>

  <div class="fav-results">
      {% for item in MyLibrary %}
      <div class="table-content">
          <div class="table-content__text">
              <div>
                  <p class="number">{{ item.num }}</p>
                  <div class="play-icon">
                      <i class="fa fa-play-circle-o"></i>
                  </div>

              </div>
          </div>
          <div class="table-content__text">
              <!-- like -->
              <div class="table-content__text">
                  <form method="POST" action="{% url 'playList:addFavorite' item.track.title %}">
                      {% csrf_token %}
                      <button class="liked" type="submit" name="liked">
                        {% if item.is_favorite %}
                          <i class="fa fa-heart"></i>
                        {% else %}
                          <i class="fa fa-heart-o"></i>
                        {% endif %}
                      </button>
                  </form>
              </div>
          </div>
          <div class="table-content__text">
              <p>{{ item.track.title }}</p>
          </div>
          <div class="table-content__text">
              <p>{{ item.track.duration }}</p>
          </div>
      </div>
      {% endfor %}
  </div>
{% endblock %}

spotify/templates/music/play.html
{% extends "base.html" %}

{% block head_content %}
    <title>Play</title>
  {% load static %}
    <link rel="stylesheet" href="{% static 'css/play.css' %}">
{% endblock%}

{% block container %}
<br><br><br><br><br><br><br>
  <div class="play__container">
    <div class="play__container-album">
      <div class="play__item-bg"></div>
      <div class="play__item-cover">
        <img src="https://i.scdn.co/image/d8316b76953bb667a8b067b64267f3b03d864952" alt="">
      </div>
      <div class="play__container-details">
        <div class="play__item-title">
          <h3>{{ data.album }}</h3>
        </div>
        <div class="play__item-album"><p>{{ data.title }}</p></div>
        <div class="play__item-artist">{{ data.artist }}</div>
        <div class="play__item-artist">{{ data.duration }}</div>
      </div>
    </div>
  </div>

{% endblock %}

spotify/templates/music/search.html
{% extends "base.html" %}

{% block head_content %}
    <title>Search</title>
  {% load static %}
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
{% endblock%}

{% block container %}
<br>
  <div class="search__container">
    <div class="search__container-title">
      <h5>Resultados de tu búsqueda</h5><br><br>
    </div>
    <div class="results__container">
      <div class="results__container-songs">
        <div class="results__container-title">
          <h3>Canción</h3><br>
        </div>
        <div class="results__container-item">
          <div class="results__item-cover">
            <img src="{{ track.image_url }}" alt="{{ track.title }}">
            <form method="POST" action="{% url 'playList:addTrack' track.title %}" >
              {% csrf_token %}
              <input type="submit" name="add" value="Agregar">
            </form><br><br><br>
          </div>
          <div class="results__item-details">
            <div class="track__item-title">{{ track.title }}</div>
            <div class="track__item-artist">{{ track.artist }}</div>
            <div class="track__item-album">{{ track.album }}</div>
            <div class="track__item-duration">{{ track.duration }}</div>
          </div>
        </div>
      </div><br><br>
      <div class="results__container-artist">
        <div class="results__container-title">
          <h3>Artista</h3><br>
        </div>
        <div class="results__container-item">
          <div class="results__item-cover">
            <img src="{{ artist.image_url }}" alt="{{ artist.artist }}">
          </div>
          <div class="results__item-details">
            <div class="artist__item-artist">{{ artist.artist }}</div>
            <div class="artist__item-genre">{{ artist.gene }}</div>
            <div class="artist__item-followers">{{ artist.followers }}</div>
            <div class="artist__item-popularity">{{ artist.popular }}</div>
          </div>
        </div>
      </div><br><br>
      <div class="results__container-albums">
        <div class="results__container-title">
          <h3>Álbum</h3><br>
        </div>
        <div class="results__container-item">
          <div class="results__item-cover">
            <img src="{{ album.image_url }}" alt="{{ album.name }}">
          </div>
          <div class="results__item-details">
            <div class="album__item-album">{{ album.name }}</div>
            <div class="album__item-artist">{{ album.artist }}</div>
            <div class="album__item-market">{{ album.market }}</div>
          </div>
        </div>
      </div><br><br><br><br><br><br><br><br><br><br><br><br>
    </div>
  </div>

{% endblock %}