config/urls.py
"""Main URLs module."""

from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    # Django Admin
    path(settings.ADMIN_URL, admin.site.urls),

    # Local
    path('', include(('spotify.users.urls', 'users'), namespace='users')),
    path('music/', include(('spotify.music.urls', 'music'), namespace='music')),
    path('playLists/', include(('spotify.playLists.urls', 'playList'), namespace='playLists')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spotify/music/urls.py
"""Music URL's."""

# Django
from django.urls import path

# Views
from spotify.music import views


urlpatterns = [
    # Management
    path(
        route='search/',
        view=views.search,
        name='search'
    ),
    path(
        route='favorites/',
        view=views.Favorites.as_view(),
        name='myFavorite'
    ),
    path(
        route='playMusic/',
        view=views.play,
        name='playMusic'
    ),
    path(
        route='myLibrary/',
        view=views.MyLibrary.as_view(),
        name='myLibrary'
    ),
]

spotify/playLists/urls.py
"""Play Lists URL's."""

# Django
from django.urls import path

# Views
from spotify.playLists import views


urlpatterns = [
    # Management
    path(
        route='addTrack/<str:title>',
        view=views.add_track,
        name='addTrack'
    ),
    path(
        route='addFavorite/<str:title>',
        view=views.add_favorite_track,
        name='addFavorite'
    ),
]

spotify/users/urls.py
"""Users URL's."""

# Django
from django.urls import path

# Views
from spotify.users import views


urlpatterns = [
    # Management

    path(
        route='',
        view=views.feed,
        name='feed'
    ),
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route="user/<str:username>/",
        view=views.UpdateProfileView.as_view(),
        name="update"
    ),
]

spotify/music/models/tracks.py
"""Tracks model."""

# Django
from django.db import models

# Utils
from spotify.utils.base_model import BaseModel


class TrackModel(BaseModel):
    """Tracks Model."""
    artist = models.CharField(
        'Artist song',
        max_length=150,
    )
    title = models.CharField(
        'Song title',
        max_length=100,
    )
    album = models.CharField(
        'Album name',
        max_length=100,
    )
    duration = models.CharField(
        'Duration time song',
        max_length=100
    )

    def __str__(self):
        """Return track name."""
        return self.title

spotify/playLists/models/usersPlayLists.py
"""Users Play Lists Relationships."""

# Django
from django.db import models

# Utils
from spotify.utils.base_model import BaseModel


class PlayLists(BaseModel):
    """Users Play List Storage."""
    user = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
    )
    track = models.ForeignKey(
        'music.TrackModel',
        on_delete=models.CASCADE,
    )
    is_favorite = models.BooleanField(
        default=False
    )

    def __str__(self):
        """Return user PlayList"""
        return (
            f"'username': {self.user}, "
            f"'is_favorite': {self.is_favorite}, "
            f"'title': {self.track.title}, "
            f"'album': {self.track.album}, "
            f"'duration': {self.track.duration}"
        )

spotify/users/models.py
"""Users model."""

# Django
from django.db import models
from django.contrib.auth.models import AbstractUser

# Utilities
from spotify.utils.base_model import BaseModel


class User(BaseModel, AbstractUser):
    """User model.

    Extend from Django's Abstract User.
    """

    email = models.EmailField('email address', unique=True)
    is_membership = models.BooleanField(
        'client',
        default=False,
        help_text=(
            'Help easily distinguish users and perform queries. '
            'Clients are the main type of user.'
        )
    )
    is_verified = models.BooleanField(
        'verified',
        default=True,
        help_text='Set to true when the user have verified its email address.'
    )
    birthday = models.DateField(
        'birthday',
        blank=True,
        null=True,
    )
    country = models.CharField(
        max_length=50,
        null=True,
        blank=True,
    )
    picture = models.ImageField(
        upload_to='users/pictures',
        blank=True,
        null=True
    )

    def __str__(self):
        """Return username."""
        return self.username

spotify/users/models/users.py
"""Users model."""

# Django
from django.db import models
from django.contrib.auth.models import AbstractUser

# Utilities
from spotify.utils.base_model import BaseModel


class User(BaseModel, AbstractUser):
    """User model.

    Extend from Django's Abstract User.
    """

    email = models.EmailField('email address', unique=True)
    is_membership = models.BooleanField(
        'client',
        default=True,
        help_text=(
            'Help easily distinguish users and perform queries. '
            'Clients are the main type of user.'
        )
    )
    is_verified = models.BooleanField(
        'verified',
        default=True,
        help_text='Set to true when the user have verified its email address.'
    )
    birthdate = models.DateField(
        'Birthdate',
        blank=True,
        null=True,
    )

    def __str__(self):
        """Return username."""
        return self.username

spotify/users/forms.py
""""Forms to User"""

# Django
from django import forms

# Models
from spotify.users.models import User


class SignupForm(forms.Form):
    """Sign up form."""

    username = forms.CharField(min_length=4, max_length=50)
    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean_email(self):
        """Email must be unique."""
        email = self.cleaned_data['email']
        email_taken = User.objects.filter(email=email).exists()
        if email_taken:
            raise forms.ValidationError('Email is already in use.')
        return email

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']
        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')
        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')
        User.objects.create_user(**data)

spotify/users/forms/users.py
""""Forms to User"""

# Django
from django import forms

# Models
from spotify.users.models import User


class SignupForm(forms.Form):
    """Sign up form."""

    username = forms.CharField(min_length=4, max_length=50)
    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use.')
        return username

    def clean_email(self):
        """Email must be unique."""
        email = self.cleaned_data['email']
        email_taken = User.objects.filter(email=email).exists()
        if email_taken:
            raise forms.ValidationError('Email is already in use.')
        return email

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']
        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')
        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')
        User.objects.create_user(**data)

spotify/music/views.py
"""Music views."""

# Django
from django.shortcuts import render
from django.views.generic import ListView

# Models
from spotify.playLists.models import PlayLists

# Utils
import json
from spotify.scraping.scraping import get_info_by_search_name, get_token


def search(request):
    """View search"""
    try:
        data_search = json.loads(get_info_by_search_name(request.GET['search'],  get_token()))
        track = data_search['track']
        artist = data_search['artist']
        album = data_search['album']
        context = {
            'track': track,
            'artist': artist,
            'album': album,
        }
    except:
        context = {
            'track': None,
            'artist': None,
            'album': None,
        }

    return render(
        request=request,
        template_name='music/search.html',
        context=context,
    )


class MyLibrary (ListView):
    """Display list user favorite Library."""
    model = PlayLists
    context_object_name = 'MyLibrary'
    template_name = 'music/myLibrary.html'

    def get_queryset(self):
        q = PlayLists.objects.filter(user__username=self.request.user.username)
        return q


def play(request):
    data = {
        'title': 'BitâKora 5: Marcas en tiempos de COVID, Elon Musk y Bose.',
        'album': 'Podcast',
        'artist': 'Nadia Molina',
        'duration': '47:89:14',
    }

    return render(
        request=request,
        template_name='music/play.html',
        context={'data': data},
    )


def save():
    pass


class Favorites (ListView):
    """Display list user favorite songs."""
    model = PlayLists
    context_object_name = 'my_favorites'
    template_name = 'music/favorites.html'

    def get_queryset(self):
        q = PlayLists.objects.filter(user__username=self.request.user.username, is_favorite=True)
        return q

spotify/playLists/views.py
"""PlayLists views."""

# Django
from django.shortcuts import redirect

# Models
from spotify.music.models import TrackModel
from spotify.playLists.models import PlayLists

# Utils
import json
from spotify.scraping.scraping import get_info_by_search_name, get_token


TOKEN = '123'
TRACK = None


def add_track(request, title):
    """View test"""
    track_exist = search_track(title)
    user = request.user

    if track_exist:
        add_in_user_library(user, TRACK)
    else:
        obtain_token()
        save_track_in_db(title)
        add_in_user_library(user, TRACK)

    return redirect('music:myLibrary')


def search_track(title):
    global TRACK
    try:
        TRACK = TrackModel.objects.get(title=title)
        return True
    except TrackModel.DoesNotExist:
        return False


def add_in_user_library(user, track):
    user_have_track = PlayLists.objects.filter(user=user, track=track)

    if not user_have_track.exists():
        PlayLists.objects.create(user=user, track=track)


def save_track_in_db(title):
    global TRACK
    data_track = json.loads(get_info_by_search_name(title, TOKEN))
    TRACK = TrackModel.objects.create(
        artist=data_track['track']['artist'],
        title=data_track['track']['title'],
        album=data_track['track']['album'],
        duration=data_track['track']['duration'],
    )


def obtain_token():
    global TOKEN
    TOKEN = get_token()


def add_favorite_track(request, title):
    PlayLists.objects.filter(user=request.user, track__title=title).update(is_favorite=True)
    return redirect('music:myLibrary')

spotify/users/views.py
"""Uses views."""

# Django
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import FormView, UpdateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Forms
from spotify.users.forms import SignupForm

# Models
from spotify.users.models import User

# Utils
import json
from spotify.scraping.scraping import get_info_by_artist_name, get_token


class LoginView(auth_views.LoginView):
    """Login view."""
    template_name = 'users/login.html'


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout view."""

    template_name = 'users/logged_out.html'


class SignupView(FormView):
    """Users sign up view."""

    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """Update profile view."""
    slug_field = 'username'
    slug_url_kwarg = 'username'

    template_name = 'users/update.html'
    model = User
    fields = ['first_name', 'last_name', 'birthday', 'country', 'picture']

    def get_object(self):
        """Return user's profile."""
        return self.request.user

    def get_success_url(self):
        """Return to user's profile."""
        username = self.object
        return reverse('users:update', kwargs={'username': username})


@login_required()
def feed(request):
    data_feed = json.loads(get_info_by_artist_name(get_token()))
    data = data_feed

    return render(
        request=request,
        template_name='index.html',
        context={'data': data},
    )

spotify/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />

    {% block head_content %}
    {% endblock%}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="icon" href=" {% static 'images/Platzi-master-logo.png' %}" />
    <link rel="stylesheet" href="{% static 'css/styles-search.css' %}" />
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;600;700;800&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}" />
    <meta name="theme-color" content="#563d7c" />
</head>

<body>
    <!-- ------------------------- Menú Lateral --------------------------- -->

    <div id="main">
      <div class="App">
        <div class="App__container">
          <div class="App__top-bar"></div>
            {% include "menuLateral.html" %}

          <!-- ------------------------- Footer - Player  --------------------------- -->

            {% include "footer.html" %}

          <!-- ------------------------- Area de Búsqueda  --------------------------- -->


                {% include "header.html" %}


                {% block container %}

                {% endblock %}

              </section>
            </main>
          </div>
        </div>
      </div>
    </div>
   <script src="https://use.fontawesome.com/6f8a610621.js"></script>

</body>
</html>

spotify/templates/footer.html
{% load static %}

 <div class="App__now-playing-bar">
            <footer class="now-playing-bar-container">
              <div class="now-playing-bar">
                <div class="now-playing-bar__left">
                  <div class="now-playing">
                    <div class="now-playing-cover">
                      <div class="icon">
                        <img
                          src="https://i.scdn.co/image/091ac8bdc0daef64f7a6a984c602ddf51c9cb186"
                          alt=""
                        />
                      </div>
                    </div>
                    <div class="now-playing-details">
                      <div class="now-playing-title">
                        <a
                          href="{% url 'music:playMusic' %}"
                          class="now-playing-track-link"
                          >BitâKora 5: Marcas en tiempos de COVID, Elon Musk y
                          Bose.</a
                        >
                      </div>
                      <div class="now-playing-artist">
                        <a href="#">Nadia Molina</a>
                      </div>
                    </div>
                    <div class="now-playing-control">
                      <button
                        class="control-button fa fa-heart"
                        title="Guardar en Tus Me Gusta"
                      ></button>
                    </div>
                  </div>
                </div>
                <div class="now-playing-bar__center">
                  <div class="player-controls">
                    <div class="player-control__buttons">
                      <div class="control-button-wrapper">
                        <button class="control-button control-button-suffle">
                          <i class="fa fa-random"></i>
                        </button>
                      </div>
                      <div class="control-button-wrapper">
                        <button class="control-button control-button-back">
                          <i class="fa fa-step-backward"></i>
                        </button>
                      </div>
                      <div class="control-button-wrapper">
                        <button
                          class="control-button control-button-play control-button-circled"
                        >
                          <i class="fa fa-play"></i>
                        </button>
                      </div>
                      <div class="control-button-wrapper">
                        <button class="control-button control-button-forward">
                          <i class="fa fa-step-forward"></i>
                        </button>
                      </div>
                      <div class="control-button-wrapper">
                        <button class="control-button control-button-repeat">
                          <i class="fa fa-retweet"></i>
                        </button>
                      </div>
                    </div>
                    <div class="playback-bar">
                      <div class="playback-bar__progress-time">
                        6:50
                      </div>
                      <div class="progress-bar__progress">
                        <div class="middle-align progress-bar__bg">
                          <div class="progress-bar__fg_wrapper">
                            <div class="progress-bar__fg"></div>
                          </div>
                          <button
                            class="middle-align progress-bar__slider"
                            style="left: 50%;"
                          ></button>
                        </div>
                      </div>
                      <div class="playback-bar__progress-time">
                        65:27
                      </div>
                    </div>
                  </div>
                </div>
                <div class="now-playing-bar__right">
                  <div class="extraControls">
                    <div class="extraControls-list">
                      <div class="control-button-wrapper">
                        <button class="control-button">
                          <i class="fa fa-bars"></i>
                        </button>
                      </div>
                      <div class="extraControls-device">
                        <button class="control-button">
                          <i class="fa fa-desktop"></i>
                        </button>
                      </div>
                      <div class="extraControls-volumeBar">
                        <button class="control-button">
                          <i class="fa fa-volume-up"></i>
                        </button>
                        <div class="progress-bar__progress">
                          <div class="middle-align progress-bar__bg">
                            <div class="progress-bar__fg_wrapper">
                              <div class="progress-bar__fg"></div>
                            </div>
                            <button
                              class="middle-align progress-bar__slider"
                            ></button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </footer>
          </div>

spotify/templates/header.html
{% load static %}

<div class="App__main-view">
            <main class="search__container">
              <section class="search__main">
                <div class="search__header">
                  <div class="search__header-input">
                    <span>
                      <i class="icon-circle-left"></i>
                    </span>
                    <span>
                      <i class="icon-circle-right"></i>
                    </span>
                    <form method="GET" action="{% url 'music:search'%}" >
                      <div class="input-container">
                        {% csrf_token %}
                          <button class="search-icon" type="submit" name="searcher">
                              <i class="icon-search"></i>
                          </button>
                        <input
                          type="text"
                          name="search"
                          id=""
                          placeholder="Buscar Artistas, canciones o podcasts"
                        />
                        </div>
                      </form>
                  </div>

                  <div class="search__header--img">
                    <a href="{% url 'users:update' user.username %}">
                      {% if user.picture %}
                      <img src="{{ user.picture.url }}" id="img-profile" />
                      {% else%}
                      <img
                        src="{% static 'images/default-profile.png' %}"
                        id="img-profile" />
                      {% endif %}
                      <span>{{ user.username }}</span>
                      <span> <i class="icon-circle-down"></i> </span
                    ></a>
                  </div>
                </div>

spotify/templates/menuLateral.html
{% load static %}

<div class="App__nav-bar">
            <nav class="App__navBar-content">
              <div class="App__navBar-banner">
                <a href="{% url 'users:feed' %}" class="logo">
                  <img src="{% static '/images/logo.png' %}" alt="Spotify" />
                </a>
              </div>
              <ul class="App__navBar-menu">
                <li class="navBar-item">
                  <a href="{% url 'users:feed' %}" class="navBar-link navBar-like--active">
                    <i class="fa fa-home icon"></i> Inicio
                  </a>
                </li><!--
                <li class="navBar-item">
                  <a href="{#% url 'music:search' %#}" class="navBar-link">
                    <i class="fa fa-search icon"></i> Buscar
                  </a>
                </li>-->
                <li class="navBar-item">
                  <a href="{% url 'music:myLibrary' %}" class="navBar-link">
                    <i class="fa fa-list icon"></i> Tu Biblioteca
                  </a>
                </li>
              </ul>
              <div class="App__list">
                <div class="App__lists-content">
                  <div class="App__playlists">
                    <h1 class="App__playlists-header">Playlists</h1>
                    <div class="App__playlist-create">
                      <button type="button">
                        <i class="fa fa-plus icon"></i>
                        <span>Crear playlist</span>
                      </button>
                    </div>
                    <div class="App__playlist-likes">
                      <a href="{% url 'music:myFavorite' %}" class="">
                        <i class="fa fa-heart icon"></i>
                        <span>Tus Me Gusta</span>
                      </a>
                    </div>
                    <hr class="App__lists-divider" />
                    <div class="App__lists_user">
                      <div class="content">
                        <ul>
                          <li class="listItem">
                            <a href="#" class="listItem__link">
                              <div class="listItem__text-wrapper">
                                Platzi Master Playlist - English
                              </div>
                            </a>
                          </li>
                          <li class="listItem">
                            <a href="#" class="listItem__link">
                              <div class="listItem__text-wrapper">
                                Pearl Jam Radio
                              </div>
                            </a>
                          </li>
                          <li class="listItem">
                            <a href="#" class="listItem__link">
                              <div class="listItem__text-wrapper">
                                Queen Radio
                              </div>
                            </a>
                          </li>
                          <li class="listItem">
                            <a href="#" class="listItem__link">
                              <div class="listItem__text-wrapper">
                                Nu Metal Generation
                              </div>
                            </a>
                          </li>
                          <li class="listItem">
                            <a href="#" class="listItem__link">
                              <div class="listItem__text-wrapper">
                                Éxitos México
                              </div>
                            </a>
                          </li>
                          <li class="listItem">
                            <a href="#" class="listItem__link">
                              <div class="listItem__text-wrapper">
                                Pop Remix
                              </div>
                            </a>
                          </li>
                          <li class="listItem">
                            <a href="#" class="listItem__link">
                              <div class="listItem__text-wrapper">
                                ¡Viva latino!
                              </div>
                            </a>
                          </li>
                          <li class="listItem">
                            <a href="#" class="listItem__link">
                              <div class="listItem__text-wrapper">
                                En el trabajo
                              </div>
                            </a>
                          </li>
                          <li class="listItem">
                            <a href="#" class="listItem__link">
                              <div class="listItem__text-wrapper">
                                Workout
                              </div>
                            </a>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div>
                <div class="navBar-item App__download-item">
                  <a href="#" class="navBar-link">
                    <i class="fa fa-arrow-circle-down icon"></i>
                    <span>Instalar aplicación</span>
                  </a>
                </div>
              </div>
            </nav>
          </div>